In [1]:
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(42)

# Ma trận chuyển vị và ma trận Hermitian 

## Ma trận chuyển vị

In [16]:
y = np.random.rand(5) # an array with 5 elements - not a column vector
print(f"y =\n {y}")
print(f"Transpose of vector y = \n {y.T}")
np.transpose(y)


y =
 [0.5612772  0.77096718 0.4937956  0.52273283 0.42754102]
Transpose of vector y = 
 [0.5612772  0.77096718 0.4937956  0.52273283 0.42754102]


array([0.5612772 , 0.77096718, 0.4937956 , 0.52273283, 0.42754102])

In [3]:
X = np.random.rand(3,4)
print(f"X =\n {X}")
print(f"Transpose of matrix X = \n {X.T}")
print(f"Transpose of matrix X = \n {np.transpose(X)}")
X.T.shape

X =
 [[0.15599452 0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451 0.30424224]]
Transpose of matrix X = 
 [[0.15599452 0.70807258 0.21233911]
 [0.05808361 0.02058449 0.18182497]
 [0.86617615 0.96990985 0.18340451]
 [0.60111501 0.83244264 0.30424224]]
Transpose of matrix X = 
 [[0.15599452 0.70807258 0.21233911]
 [0.05808361 0.02058449 0.18182497]
 [0.86617615 0.96990985 0.18340451]
 [0.60111501 0.83244264 0.30424224]]


(4, 3)

## Ma trận Hermitian

For a given matrix $\mathbf{A}$, conjugate transpose of matrix $\mathbf{A}$ is denoted by $\mathbf{A}^H$. We have 
$$ \left[\mathbf{A}^H\right]_{ij} = \left[\mathbf{A}_{ji}\right]^*$$
If $\left[\mathbf{A}_{ji}\right] = a + bi$ then $\left[\mathbf{A}_{ji}\right]^* = a- bi$

In [4]:
Z = np.random.rand(2,3) + 1j * np.random.rand(2,3)
print(f"Z = \n {Z}")
print(f"conjugate transpose of matrix X = \n {np.conjugate(Z)}")

Z = 
 [[0.52475643+0.36636184j 0.43194502+0.45606998j 0.29122914+0.78517596j]
 [0.61185289+0.19967378j 0.13949386+0.51423444j 0.29214465+0.59241457j]]
conjugate transpose of matrix X = 
 [[0.52475643-0.36636184j 0.43194502-0.45606998j 0.29122914-0.78517596j]
 [0.61185289-0.19967378j 0.13949386-0.51423444j 0.29214465-0.59241457j]]


# Định thức của một ma trận

In [5]:
X = np.random.rand(3,3) # real matrix
Z = np.random.rand(3,3) + 1j * np.random.rand(3,3) # bthg a + bi , trong code thì nó là a + bj

print(f"determinant of matrix X = {np.linalg.det(X)}")
print(f"determinant of matrix Z = {np.linalg.det(Z)}")

determinant of matrix X = 0.33361391401291307
determinant of matrix Z = (-0.2269402143831396-0.6272484144519535j)


# Nghịch đảo của ma trận

In [6]:
print(f"inverse matrix of X = \n {np.linalg.inv(X)}")  # inv là viết tắt của inverse
print(f"inverse matrix of Z = \n {np.linalg.inv(Z)}")

inverse matrix of X = 
 [[-0.60388715 -0.02216992  1.27349873]
 [ 2.32082841 -0.39960665 -0.10119824]
 [-2.23989741  1.42976115  0.0136516 ]]
inverse matrix of Z = 
 [[ 1.63837522-0.59427987j  0.36479681+0.66945304j -1.15457084-0.37676077j]
 [-0.48862299+0.03701774j -0.82888326-0.51084939j  1.40577688+0.10624513j]
 [-1.21766799+0.24985996j  0.57181347-0.61843465j  0.24477981-0.01899266j]]


### Giả nghịch đảo của một ma trận

In [19]:
# create matrix X with determinant equal to 0 
X = np.array([[1,3], [2,6]]) 
# 1 3
# 2 6 
#X_dagger = np.linalg.inv(X) # error 
X_dagger = np.linalg.pinv(X) # pseudo inverse
X_dagger
# ma trận giả nghịch đảo. Khi mà det(X) = 0 , tức là X không gồm các hàng độc lập tuyến tính
#nhưng mà có cía phương trình Xy = b => y = giả nghịch đảo(X) * b.  
# ma trận gì , có thể các hàng nó tỉ lệ vs ban đầu 

array([[0.02, 0.04],
       [0.06, 0.12]])

# Giá trị riêng và vector riêng của ma trận

In [20]:
eigenvalues, eigenvectors = np.linalg.eig(Z) # eigen, hàm này nó trả về 2 list, list đàu tiên là giá trị riêng, còn list thứ 2 là vector riêng
print(f"eigenvalues of matrix Z is \n{eigenvalues}")
print(f"eigenvectors of matrix Z is \n{eigenvectors}")

eigenvalues of matrix Z is 
[ 1.29944647+2.05820459j  0.39526551+0.11468956j -0.66437936+0.04418093j]
eigenvectors of matrix Z is 
[[ 0.3582411 -0.10339026j  0.75332502+0.j         -0.25789114-0.18960835j]
 [ 0.68184949+0.j         -0.3602117 -0.02058259j  0.80097752+0.j        ]
 [ 0.62918124-0.01363861j -0.54954681+0.01798914j -0.46031516+0.20996618j]]


# Norm (chuẩn của một vector/ma trận)

In [9]:
y = np.random.rand(5)
print(f"y = {y}")
print(f"l_2 norm of y = {np.linalg.norm(y)}") # mặc định thì là l2
print(f"l_1 norm of y = {np.linalg.norm(y, 1)}")
print(f"l_infty norm of y = {np.linalg.norm(y, np.inf)}")

y = [0.0884925  0.19598286 0.04522729 0.32533033 0.38867729]
l_2 norm of y = 0.5524450855772945
l_1 norm of y = 1.0437102738343491
l_infty norm of y = 0.388677289689482


In [32]:
X = -1 + 2 * np.random.rand(3,4) # các phần tử -1 + 2 * rand(); 0<= rand() <=1. Khi đó -1 + 2 * rand() thuộc [-1,1]
#broadcasting

"""
norm calculated based on built-in function
"""
print(f"X = {X}")
print(f"l_2 frobenius norm of matrix X = {np.linalg.norm(X)}")
norm = np.linalg.norm(X) # cách 1 là dùng hàm
"""
norm calculated based on definition
"""
check_norm1 = np.sqrt(np.sum(np.reshape(np.square(X), (1,-1)))) #cách 2: dòng này là tính Frobenius norm theo định nghĩa 
print(f"norm calculated based on definition : {check_norm1}") 
"""
norm calculated based on corollary of trace
"""
print(f"norm calculated based on corollary of trace ( ||X|| = trace(XX^T) ): {np.sqrt(np.trace(np.matmul(X,X.T)))}") 
# cách 3: dùng tính chất norm(X) = trace(XX^T) = trace(X^TX) 

"""check"""
print(norm == check_norm1) # lí do là việc tính toán với số thực có thể dẫn đến sai số 
print(np.isclose(norm,check_norm1)) #always true chỉ cần là gần nhau ở mức 1e-8 (mặc định) thì nó là bằng nhau rồi
# np.allclose => check từng phần tử của ma trận có bằng nhau không



X = [[ 0.31522578  0.13661721 -0.81265046 -0.26456839]
 [-0.46959526 -0.51202071  0.94602111 -0.21380455]
 [ 0.78409311  0.26227725  0.58962261  0.00527419]]
l_2 frobenius norm of matrix X = 1.8174311585283518
norm calculated based on definition : 1.817431158528352
norm calculated based on corollary of trace ( ||X|| = trace(XX^T) ): 1.8174311585283518
False
True


In [22]:
# A có size 3x1 , B có size là 1x4 => A + B sẽ có size là 3x4 , A lặp ra 4 cột giống nhau, B lặp ra 3 hàng giống nhau để cộng 
a = np.random.rand(3).reshape(3,-1)
b = np.random.rand(4).reshape(1,-1)

a + b

array([[0.47809039, 0.32627214, 0.53904368, 0.41051352],
       [0.63918109, 0.48736283, 0.70013438, 0.57160421],
       [0.9843493 , 0.83253105, 1.04530259, 0.91677243]])

# Mathercise 2 
Given function 
    $$
        f(x,y,z) = 4x_1 + 6x_2^2 + 5x_2x_3 + 9x_3^4
    $$
    and $z = (2,4,7.5) \in \mathbb{R}^3$. Compute the value of $f$ after using **_Gradient Descent_** method 2 times, starting from $z$ with **_learning rate_** equal to $0.1$.

In [34]:
def f(x):
    return 4 * x[0] + 6 * (x[1] ** 2) + 5 * x[1] * x[2] + 9 * (x[2] ** 4)

def gradient(x):
    return np.array([4, 12 * x[1] + 5 * x[2], 36 * (x[2] ** 3)])

z = np.array([2.0,4.0,7.5])

learning_rate = 1e-3

#first iteration
z1 = z - learning_rate * gradient(z)
print(f(z1))
#second iteration 
z2 = z1 - learning_rate * gradient(z1)
print(f(z2))
# chú ý : sau khi dùng GD , giá trị của f2 tăng lên => điều này có nghĩa là 
# dùng GD không hiệu quả, thuật toán này ko hiệu quả 
# hoặc là do learning_rate qúa lớn


31382.257035938477
51069.90896380637
