# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [87]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [88]:
# Create a 1-dimensional NumPy array using np.array()
array1d = np.array([1, 2, 3])


# Create a 2-dimensional NumPy array using np.array()
array2d = np.array([[1, 2, 3], [4,5,6]])


# Create a 3-dimensional Numpy array using np.array()
array3d = np.array([[[1, 2, 3], [4,5,6]], [[7,8,9], [1,1,1]]])


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [89]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(f"shape: {array1d.shape}", f"number of dimensions: {array1d.ndim}", f"data type: {array1d.dtype}", f"size: {array1d.size}", f"type: {type(array1d)}", sep="\n")

shape: (3,)
number of dimensions: 1
data type: int32
size: 3
type: <class 'numpy.ndarray'>


In [90]:
# Attributes of 2-dimensional array
print(f"shape: {array2d.shape}", f"number of dimensions: {array2d.ndim}", f"data type: {array2d.dtype}", f"size: {array2d.size}", f"type: {type(array2d)}", sep="\n")

shape: (2, 3)
number of dimensions: 2
data type: int32
size: 6
type: <class 'numpy.ndarray'>


In [91]:
# Attributes of 3-dimensional array
print(f"shape: {array3d.shape}", f"number of dimensions: {array3d.ndim}", f"data type: {array3d.dtype}", f"size: {array3d.size}", f"type: {type(array3d)}", sep="\n")

shape: (2, 2, 3)
number of dimensions: 3
data type: int32
size: 12
type: <class 'numpy.ndarray'>


In [92]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(array2d)
df

0  1  2
0  1  2  3
1  4  5  6

In [93]:
# Create an array of shape (10, 2) with only ones
arr1 = np.ones((10,2), dtype="int32")

In [94]:
# Create an array of shape (7, 2, 3) of only zeros
arr0 = np.zeros((7,2,3), dtype='int32')

In [95]:
# Create an array within a range of 0 and 100 with step 3
arr103 = np.arange(0, 100, 3)
arr103

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [96]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr_rand = np.random.randint(0, 10, (7,2))
arr_rand

array([[0, 3],
       [8, 2],
       [8, 6],
       [3, 2],
       [9, 4],
       [4, 2],
       [8, 3]])

In [97]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr_rand_float = np.random.rand(3,5)
arr_rand_float

array([[0.67251846, 0.75237453, 0.79157904, 0.78961814, 0.0912061 ],
       [0.4944203 , 0.05755876, 0.54952888, 0.4415305 , 0.88770418],
       [0.35091501, 0.11706702, 0.14299168, 0.76151063, 0.61821806]])

In [98]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr_rand_1 = np.random.randint(0,10, size=(4,6))
arr_rand_1

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

- Values in the randomized array still remains the same.
- Because the random function takes seed as the only parameter to calculate the output, computer cannot ramdomize.

In [99]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr_rand_2 = np.random.randint(1,10, size=(3,7))

# Find the unique numbers in the array you just created
list_rand_2 = list(arr_rand_2.flatten())
print(arr_rand_2)
print(list(filter(lambda x: list_rand_2.count(x)== 1,list_rand_2)))


[[9 1 3 7 4 9 3]
 [5 3 7 5 9 7 2]
 [4 9 2 9 5 2 4]]
[1]


In [100]:
# Find the 0'th index of the latest array you created
arr_rand_2[0]


array([9, 1, 3, 7, 4, 9, 3])

In [101]:
# Get the first 2 rows of latest array you created
arr_rand_2[0:2,]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [102]:
# Get the first 2 values of the first 2 rows of the latest array
arr_rand_2[0:2, 0:2]

array([[9, 1],
       [5, 3]])

In [103]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr_rand_3 = np.random.randint(0,10, size=(3,5))
arr_ones = np.ones(shape=(3,5), dtype='int32')
arr_rand_3

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]])

In [104]:
# Add the two arrays together
arr_rand_3 + arr_ones

array([[ 7,  8,  3,  1,  4],
       [ 2,  8,  4,  2,  6],
       [ 6, 10,  4,  6,  2]])

In [105]:
# Create another array of ones of shape (5, 3)
arr_ones_1 = np.ones(shape=(5,3), dtype='int32')

In [106]:
# Try add the array of ones and the other most recent array together
# arr_ones_1 + arr_ones

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

- 2 array must have the same shape to be added up properly

In [107]:
# Create another array of ones of shape (3, 5)
arr_ones_1 = np.ones(shape=(3,5), dtype='int32')

In [110]:
# Subtract the new array of ones from the other most recent array
arr_rand_3 - arr_ones

array([[ 5,  6,  1, -1,  2],
       [ 0,  6,  2,  0,  4],
       [ 4,  8,  2,  4,  0]])

In [111]:
# Multiply the ones array with the latest array
arr_rand_3 * arr_ones

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]])

In [112]:
# Take the latest array to the power of 2 using '**'
arr_rand_3 ** 2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [113]:
# Do the same thing with np.square()
np.square(arr_rand_3)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [114]:
# Find the mean of the latest array using np.mean()
np.mean(arr_rand_3)

3.8666666666666667

In [115]:
# Find the maximum of the latest array using np.max()
np.max(arr_rand_3)

9

In [116]:
# Find the minimum of the latest array using np.min()
np.min(arr_rand_3)

0

In [117]:
# Find the standard deviation of the latest array
np.std(arr_rand_3)

2.578543947441829

In [118]:
# Find the variance of the latest array
np.var(arr_rand_3)

6.648888888888889

In [120]:
# Reshape the latest array to (3, 5, 1)
arr_rand_3.reshape((3,5,1))
arr_rand_3

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]])

In [121]:
# Transpose the latest array
arr_rand_3.transpose()

array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]])

What does the transpose do?
- make i-th row becomes i-th column

In [124]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr_rand_4 = np.random.randint(0,10, size=(3,3))
arr_rand_5 = np.random.randint(0,10, size=(3,2))
print(arr_rand_4, arr_rand_5, sep='\n')


[[0 8 6]
 [8 7 0]
 [7 7 2]]
[[0 7]
 [2 2]
 [0 4]]


In [123]:
# Perform a dot product on the two newest arrays you created
np.dot(arr_rand_4, arr_rand_5)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [128]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr_rand_6 = np.random.randint(0,10, size=(4,3))
arr_rand_7 = np.random.randint(0,10, size=(4,3))

In [129]:
# Perform a dot product on the two newest arrays you created
# np.dot(arr_rand_6, arr_rand_7)

It doesn't work. How would you fix it?

In [132]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
arr_rand_6 = arr_rand_6.transpose()
np.dot(arr_rand_6, arr_rand_7)

array([[123, 120,  96],
       [ 74,  75,  81],
       [109,  76, 116]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [133]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr_rand_8 = np.random.randint(0,10, size=(3,4))
arr_rand_9 = np.random.randint(0,10, size=(3,4))

print(arr_rand_8, arr_rand_9, sep="\n")

[[6 8 6 0]
 [0 8 8 3]
 [8 2 6 5]]
[[7 8 4 0]
 [2 9 7 5]
 [7 8 3 0]]


In [134]:
# Compare the two arrays with '>'
arr_rand_9> arr_rand_8

array([[ True, False, False, False],
       [ True,  True, False,  True],
       [False,  True, False, False]])

What happens when you compare the arrays with `>`?

In [135]:
# Compare the two arrays with '>='

arr_rand_9>= arr_rand_8

array([[ True,  True, False,  True],
       [ True,  True, False,  True],
       [False,  True, False, False]])

In [136]:
# Find which elements of the first array are greater than 7
arr_rand_8 > 7

array([[False,  True, False, False],
       [False,  True,  True, False],
       [ True, False, False, False]])

In [137]:
# Which parts of each array are equal? (try using '==')
arr_rand_8 == arr_rand_9

array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [140]:
# Sort one of the arrays you just created in ascending order
arr_rand_8.sort()
arr_rand_8

array([[0, 6, 6, 8],
       [0, 3, 8, 8],
       [2, 5, 6, 8]])

In [144]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr_rand_9)

array([[3, 2, 0, 1],
       [0, 3, 2, 1],
       [3, 2, 0, 1]], dtype=int64)

In [143]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr_rand_9)

5

In [145]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr_rand_9)

3

In [146]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr_rand_9, axis=1)

array([1, 1, 1], dtype=int64)

In [147]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr_rand_9, axis=0)

array([1, 0, 2, 0], dtype=int64)

In [155]:
# Create an array of normally distributed random numbers
normal_arr = np.random.normal(10.01, 20, size=(100,))
normal_arr.sort()
normal_arr

array([-57.27191053, -39.17386724, -28.28814739, -24.85570494,
       -24.59630621, -23.19234841, -21.71927237, -19.84202729,
       -19.22513312, -18.77923193, -17.0390111 , -17.00443906,
       -16.83625653, -16.74689648, -13.51254956, -13.42953709,
       -13.38634064, -12.07443577, -11.31642956, -10.80700307,
        -9.33222109,  -7.5793568 ,  -7.43207531,  -6.87215465,
        -5.95470436,  -5.82439957,  -5.57160458,  -4.73858933,
        -4.02626885,  -4.02399954,  -3.41047822,  -3.12057903,
        -2.91598999,  -2.73471064,  -2.3057169 ,  -2.00209362,
        -1.15840739,  -0.97516363,   0.32248616,   1.5664565 ,
         1.93890086,   2.34024948,   3.15822264,   3.54254402,
         3.81513793,   3.84644093,   4.28306968,   4.66198724,
         5.33593641,   6.26550087,   6.73269473,   7.14433483,
         7.85030071,   7.93317765,  10.89701115,  10.9221568 ,
        11.12144314,  11.15825896,  11.21465843,  12.85100184,
        13.33859072,  14.38366185,  14.51470706,  14.99

In [157]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.